-- =========================
-- 検索用ビュー
-- =========================
CREATE OR REPLACE VIEW PRODUCT_SEARCH_VIEW (
    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_PRICE,
    PRODUCT_STOCK,
    PRODUCT_IMAGE,
    MAKER_NAME,
    CATEGORY,
    CATEGORY_ID,
    CPU_GEN,
    CPU_CORE,
    CPU_THREAD,
    CPU_CLOCK,
    GPU_SERIES,
    GPU_CHIP,
    GPU_VRAM,
    MEMORY_GEN,
    MEMORY_CAPACITY,
    MB_CHIPSET,
    MB_SIZE,
    SSD_CAPACITY,
    SSD_TYPE,
    HDD_CAPACITY,
    HDD_RPM,
    SEARCH_TEXT
) AS
    SELECT
        P.PRODUCT_ID,
        P.NAME  AS PRODUCT_NAME,
        P.PRICE AS PRODUCT_PRICE,
        P.STOCK AS PRODUCT_STOCK,
        P.IMAGE AS PRODUCT_IMAGE,
        MK.VALUE AS MAKER_NAME,
        'CPU' AS CATEGORY,
        C.CPU_ID AS CATEGORY_ID,
        CG.VALUE AS CPU_GEN,
        CC.VALUE AS CPU_CORE,
        CT.VALUE AS CPU_THREAD,
        CCL.VALUE AS CPU_CLOCK,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS GPU_SERIES,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS GPU_CHIP,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS GPU_VRAM,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS MEMORY_GEN,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS MEMORY_CAPACITY,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS MB_CHIPSET,
        CAST(NULL AS VARCHAR2(50 CHAR))  AS MB_SIZE,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS SSD_CAPACITY,
        CAST(NULL AS VARCHAR2(50 CHAR))  AS SSD_TYPE,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS HDD_CAPACITY,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS HDD_RPM,
        TRIM(
            P.NAME || ' ' || MK.VALUE || ' ' ||
            CG.VALUE || ' ' || CC.VALUE || ' ' || CT.VALUE || ' ' || CCL.VALUE
        ) AS SEARCH_TEXT
    FROM CPU C
    JOIN PRODUCT P ON C.PRODUCT_ID = P.PRODUCT_ID
    JOIN MAKER MK ON P.MAKER_ID = MK.MAKER_ID
    JOIN CPU_GEN CG ON C.GEN_ID = CG.GEN_ID
    JOIN CPU_CORE CC ON C.CORE_ID = CC.CORE_ID
    JOIN CPU_THREAD CT ON C.THREAD_ID = CT.THREAD_ID
    JOIN CPU_CLOCK CCL ON C.CLOCK_ID = CCL.CLOCK_ID

    UNION ALL

    SELECT
        P.PRODUCT_ID,
        P.NAME  AS PRODUCT_NAME,
        P.PRICE AS PRODUCT_PRICE,
        P.STOCK AS PRODUCT_STOCK,
        P.IMAGE AS PRODUCT_IMAGE,
        MK.VALUE AS MAKER_NAME,
        'GPU' AS CATEGORY,
        G.GPU_ID AS CATEGORY_ID,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS CPU_GEN,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS CPU_CORE,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS CPU_THREAD,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS CPU_CLOCK,
        GS.VALUE AS GPU_SERIES,
        GC.VALUE AS GPU_CHIP,
        GV.VALUE AS GPU_VRAM,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS MEMORY_GEN,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS MEMORY_CAPACITY,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS MB_CHIPSET,
        CAST(NULL AS VARCHAR2(50 CHAR))  AS MB_SIZE,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS SSD_CAPACITY,
        CAST(NULL AS VARCHAR2(50 CHAR))  AS SSD_TYPE,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS HDD_CAPACITY,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS HDD_RPM,
        TRIM(
            P.NAME || ' ' || MK.VALUE || ' ' ||
            GS.VALUE || ' ' || GC.VALUE || ' ' || GV.VALUE
        ) AS SEARCH_TEXT
    FROM GPU G
    JOIN PRODUCT P ON G.PRODUCT_ID = P.PRODUCT_ID
    JOIN MAKER MK ON P.MAKER_ID = MK.MAKER_ID
    JOIN GPU_SERIES GS ON G.SERIES_ID = GS.SERIES_ID
    JOIN GPU_CHIP GC ON G.CHIP_ID = GC.CHIP_ID
    JOIN GPU_VRAM GV ON G.VRAM_ID = GV.VRAM_ID

    UNION ALL

    SELECT
        P.PRODUCT_ID,
        P.NAME  AS PRODUCT_NAME,
        P.PRICE AS PRODUCT_PRICE,
        P.STOCK AS PRODUCT_STOCK,
        P.IMAGE AS PRODUCT_IMAGE,
        MK.VALUE AS MAKER_NAME,
        'MEMORY' AS CATEGORY,
        M.MEMORY_ID AS CATEGORY_ID,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS CPU_GEN,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS CPU_CORE,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS CPU_THREAD,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS CPU_CLOCK,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS GPU_SERIES,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS GPU_CHIP,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS GPU_VRAM,
        MG.VALUE AS MEMORY_GEN,
        MC.VALUE AS MEMORY_CAPACITY,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS MB_CHIPSET,
        CAST(NULL AS VARCHAR2(50 CHAR))  AS MB_SIZE,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS SSD_CAPACITY,
        CAST(NULL AS VARCHAR2(50 CHAR))  AS SSD_TYPE,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS HDD_CAPACITY,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS HDD_RPM,
        TRIM(
            P.NAME || ' ' || MK.VALUE || ' ' ||
            MG.VALUE || ' ' || MC.VALUE
        ) AS SEARCH_TEXT
    FROM MEMORY M
    JOIN PRODUCT P ON M.PRODUCT_ID = P.PRODUCT_ID
    JOIN MAKER MK ON P.MAKER_ID = MK.MAKER_ID
    JOIN MEMORY_GEN MG ON M.GEN_ID = MG.GEN_ID
    JOIN MEMORY_CAPACITY MC ON M.CAPACITY_ID = MC.CAPACITY_ID

    UNION ALL

    SELECT
        P.PRODUCT_ID,
        P.NAME  AS PRODUCT_NAME,
        P.PRICE AS PRODUCT_PRICE,
        P.STOCK AS PRODUCT_STOCK,
        P.IMAGE AS PRODUCT_IMAGE,
        MK.VALUE AS MAKER_NAME,
        'MOTHER_BOARD' AS CATEGORY,
        MB.MOTHER_BOARD_ID AS CATEGORY_ID,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS CPU_GEN,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS CPU_CORE,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS CPU_THREAD,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS CPU_CLOCK,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS GPU_SERIES,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS GPU_CHIP,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS GPU_VRAM,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS MEMORY_GEN,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS MEMORY_CAPACITY,
        MBC.VALUE AS MB_CHIPSET,
        MBS.VALUE AS MB_SIZE,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS SSD_CAPACITY,
        CAST(NULL AS VARCHAR2(50 CHAR))  AS SSD_TYPE,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS HDD_CAPACITY,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS HDD_RPM,
        TRIM(
            P.NAME || ' ' || MK.VALUE || ' ' ||
            MBC.VALUE || ' ' || MBS.VALUE
        ) AS SEARCH_TEXT
    FROM MOTHER_BOARD MB
    JOIN PRODUCT P ON MB.PRODUCT_ID = P.PRODUCT_ID
    JOIN MAKER MK ON P.MAKER_ID = MK.MAKER_ID
    JOIN MOTHER_BOARD_CHIPSET MBC ON MB.CHIPSET_ID = MBC.CHIPSET_ID
    JOIN MOTHER_BOARD_SIZE MBS ON MB.SIZE_ID = MBS.SIZE_ID

    UNION ALL

    SELECT
        P.PRODUCT_ID,
        P.NAME  AS PRODUCT_NAME,
        P.PRICE AS PRODUCT_PRICE,
        P.STOCK AS PRODUCT_STOCK,
        P.IMAGE AS PRODUCT_IMAGE,
        MK.VALUE AS MAKER_NAME,
        'SSD' AS CATEGORY,
        S.SSD_ID AS CATEGORY_ID,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS CPU_GEN,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS CPU_CORE,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS CPU_THREAD,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS CPU_CLOCK,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS GPU_SERIES,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS GPU_CHIP,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS GPU_VRAM,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS MEMORY_GEN,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS MEMORY_CAPACITY,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS MB_CHIPSET,
        CAST(NULL AS VARCHAR2(50 CHAR))  AS MB_SIZE,
        SC.VALUE AS SSD_CAPACITY,
        ST.VALUE AS SSD_TYPE,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS HDD_CAPACITY,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS HDD_RPM,
        TRIM(
            P.NAME || ' ' || MK.VALUE || ' ' ||
            SC.VALUE || ' ' || ST.VALUE
        ) AS SEARCH_TEXT
    FROM SSD S
    JOIN PRODUCT P ON S.PRODUCT_ID = P.PRODUCT_ID
    JOIN MAKER MK ON P.MAKER_ID = MK.MAKER_ID
    JOIN STORAGE_CAPACITY SC ON S.CAPACITY_ID = SC.CAPACITY_ID
    JOIN SSD_TYPE ST ON S.TYPE_ID = ST.TYPE_ID

    UNION ALL

    SELECT
        P.PRODUCT_ID,
        P.NAME  AS PRODUCT_NAME,
        P.PRICE AS PRODUCT_PRICE,
        P.STOCK AS PRODUCT_STOCK,
        P.IMAGE AS PRODUCT_IMAGE,
        MK.VALUE AS MAKER_NAME,
        'HDD' AS CATEGORY,
        H.HDD_ID AS CATEGORY_ID,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS CPU_GEN,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS CPU_CORE,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS CPU_THREAD,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS CPU_CLOCK,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS GPU_SERIES,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS GPU_CHIP,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS GPU_VRAM,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS MEMORY_GEN,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS MEMORY_CAPACITY,
        CAST(NULL AS VARCHAR2(100 CHAR)) AS MB_CHIPSET,
        CAST(NULL AS VARCHAR2(50 CHAR))  AS MB_SIZE,
        CAST(NULL AS VARCHAR2(30 CHAR))  AS SSD_CAPACITY,
        CAST(NULL AS VARCHAR2(50 CHAR))  AS SSD_TYPE,
        SC.VALUE AS HDD_CAPACITY,
        HR.VALUE AS HDD_RPM,
        TRIM(
            P.NAME || ' ' || MK.VALUE || ' ' ||
            SC.VALUE || ' ' || HR.VALUE
        ) AS SEARCH_TEXT
    FROM HDD H
    JOIN PRODUCT P ON H.PRODUCT_ID = P.PRODUCT_ID
    JOIN MAKER MK ON P.MAKER_ID = MK.MAKER_ID
    JOIN STORAGE_CAPACITY SC ON H.CAPACITY_ID = SC.CAPACITY_ID
    JOIN HDD_RPM HR ON H.RPM_ID = HR.RPM_ID
;